@startuml
!include ../_common.style
title Centralized Medical Documents (Consult the medical document of a patient)
center footer CMD - sequence diagram

actor "Doctor" as D
participant "_: DocumentView" as DV
participant "_: DocumentController" as DC
participant "_: Document" as DO
participant "_: DocumentDAO" as DD

D -> DV :Login()
activate DV
DV -> DC :detail()
deactivate DV
activate DC
DC -> DC:verifyUserRole()
DC -> DD :this()
deactivate DC
activate DD

DD -> DD:get()

DD --> DO:this()
activate DO
DO --> DC: return(d : Document)
activate DC
deactivate DO

DC --> DV: return viewDocument(d :  Document)
deactivate DC
activate DV

DV --> D
deactivate DV

@enduml