@startuml
!include ../_common.style
title Centralized Medical Documents ("Consult your medical document")
center footer CMD - sequence diagram
actor "Patient" as P

participant "_:DocumentView" as DV
participant "_:DocumentController" as DC
participant "_:Document" as D
participant "_:DocumentDAO" as DD



P -> DC : Login()
activate DC
DC -> DC:verifyUserRole()
DC -> DD : this()
activate DD

DD -> DD: get()

D<-- DD: this()

D --> DC : return Document d
deactivate D
DC --> DV : details.jsp
activate DV
DV --> P :


@enduml