@startuml

participant Controller as Controller

participant AbstractService as Service

participant AbstractDAO as DAO


Controller -> Service : getInstance();
opt Serviceinstance == null
Service -> Service : new AbstractService\nthis.ServiceInstance
end
Service -> DAO : getInstance();
opt DAOinstance == null
DAO -> DAO : new AbstractDAO()\n this.DAOinstance
end
DAO -> Service: return DAOinstance
Service -> Controller : return ServiceInstance


@enduml